#!/usr/bin/env python3
"""Backfill word precision/F1 and token stats on existing OCR metrics CSVs."""

from __future__ import annotations

import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT))

import pandas as pd

from src.data.dataset_loader import iter_manifest
from src.ocr.ocr_metrics import (
    duplicate_token_ratio,
    predicted_token_count,
    word_f1,
    word_precision,
    word_recall,
)
from src.utils.paths import data_path, outputs_path, repo_path


def _gt_map(manifest_path: Path) -> dict[str, str]:
    return {r["image_id"]: r.get("ocr_gt_text", "") for r in iter_manifest(manifest_path)}


def backfill_csv(csv_path: Path, gt_by_image: dict[str, str]) -> None:
    df = pd.read_csv(csv_path)
    if "raw_prediction" not in df.columns:
        print(f"Skip {csv_path.name}: no raw_prediction")
        return

    for idx, row in df.iterrows():
        if row.get("not_applicable") in (True, "True"):
            continue
        if row.get("dry_run") in (True, "True"):
            continue
        pred = str(row.get("raw_prediction", "") or "")
        gt = gt_by_image.get(row["image_id"], "")
        df.at[idx, "word_recall"] = word_recall(pred, gt)
        df.at[idx, "word_precision"] = word_precision(pred, gt)
        df.at[idx, "word_f1"] = word_f1(pred, gt)
        df.at[idx, "predicted_token_count"] = predicted_token_count(pred)
        df.at[idx, "duplicate_token_ratio"] = duplicate_token_ratio(pred)

    df.to_csv(csv_path, index=False)
    print(f"Backfilled {csv_path}")


def main() -> None:
    manifest = data_path("manifests", "textocr_pilot.jsonl")
    gt = _gt_map(manifest)
    metrics_dir = outputs_path("metrics")
    for csv in sorted(metrics_dir.glob("ocr_metrics*pilot*.csv")):
        backfill_csv(csv, gt)

    # Sync paper tables copy if present
    pilot_copy = repo_path("paper", "latex_v2", "tables", "table_ocr_budget.csv")
    if pilot_copy.exists():
        pass  # regenerated by make_paper_assets


if __name__ == "__main__":
    main()
